service: spotify_samples_playlist
provider:
  name: aws
  runtime: python3.8

stage: dev
region: us-east-1

plugins:
  - serverless-offline

functions:
  get_samples:
    handler: src/handlers/get_samples.handler
    events:
      - http:
          method: get
          path: samples
          cors: true
