service: spotify_samples_playlist
provider:
  name: aws
  runtime: python3.8

stage: dev
region: us-east-1

plugins:
  - serverless-offline

custom:
  cors:
    origin: '*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent

functions:
  get_samples:
    handler: src/handlers/get_samples.handler
    events:
      - http:
          method: get
          path: samples
          cors: ${self:custom.cors}
